default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.DATABASE[Rails.env.upcase.to_sym][:SNM_DATABASE_USERNAME] %>
  password: <%= Rails.application.credentials.DATABASE[Rails.env.upcase.to_sym][:SNM_DATABASE_PASSWORD] %>
  database: <%= Rails.application.credentials.DATABASE[Rails.env.upcase.to_sym][:SNM_DATABASE_NAME] %>
  host: <%= Rails.application.credentials.DATABASE[Rails.env.upcase.to_sym][:SNM_DATABASE_HOST] %>
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
